Repository usnistgov/WIPP-backend, pull requests merged in 2020-08, with the labels that each got.

#153 feat: fix swagger dependencies conflict, upgrade to springfox 3.0 rel…
  wipp-backend-application/src/main/java/gov/nist/itl/ssd/wipp/backend/Application.java
  wipp-backend-argo-workflows/src/main/java/gov/nist/itl/ssd/wipp/backend/argo/workflows/workflow/WorkflowExitController.java
  wipp-backend-argo-workflows/src/main/java/gov/nist/itl/ssd/wipp/backend/argo/workflows/workflow/WorkflowSubmitController.java
  wipp-backend-core/pom.xml
  wipp-backend-core/src/main/java/gov/nist/itl/ssd/wipp/backend/core/model/workflow/WorkflowCopyController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollectionDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/csv/CsvController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/csv/CsvUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionCatalogImportController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionCopyController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/metadatafiles/MetadataFileController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/metadatafiles/MetadataFileUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/jupyternotebook/NotebookGetFileController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/jupyternotebook/NotebookImportController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/pyramid/PyramidFetchingController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/pyramid/timeslices/PyramidTimeSliceController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/pyramidannotation/timeslices/PyramidAnnotationTimeSliceController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorStatisticsController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/timeslices/StitchingVectorTimeSliceController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/tensorflowmodels/TensorflowModelDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/visualization/VisualizationDownloadController.java
Labels: dependency-upgrade

#151 feat: added generic data data type
  wipp-backend-application/pom.xml
  wipp-backend-application/src/main/resources/application.properties
  wipp-backend-core/src/main/java/gov/nist/itl/ssd/wipp/backend/core/CoreConfig.java
  wipp-backend-data/pom.xml
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericData.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataDataHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataRepository.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataResourceProcessor.java
Labels: feature

#154 Feature/fix generic data
  wipp-backend-core/pom.xml
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataResourceProcessor.java
Labels: bug
