Repository usnistgov/WIPP-backend, pull requests merged in 2020-01, with the labels that each got.

#117 fix: temporarily disable because of breaking changes in current version
  wipp-backend-application/src/main/java/gov/nist/itl/ssd/wipp/backend/Application.java
  wipp-backend-argo-workflows/src/main/java/gov/nist/itl/ssd/wipp/backend/argo/workflows/workflow/WorkflowExitController.java
  wipp-backend-argo-workflows/src/main/java/gov/nist/itl/ssd/wipp/backend/argo/workflows/workflow/WorkflowSubmitController.java
  wipp-backend-core/pom.xml
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollectionDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionCopyController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/metadatafiles/MetadataFileController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/metadatafiles/MetadataFileUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/jupyternotebook/NotebookGetFileController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/jupyternotebook/NotebookImportController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/pyramid/PyramidFetchingController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/pyramid/timeslices/PyramidTimeSliceController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorStatisticsController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/timeslices/StitchingVectorTimeSliceController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/tensorflowmodels/TensorflowModelDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/visualization/VisualizationDownloadController.java
Labels: bug

#118 fix: pyramid visualization object serialization
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/visualization/manifest/layers/BaseUrlManualRefSerializer.java
Labels: bug

#113 feat: handle upload of multiple csv files in csv collection
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollectionLogic.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollectionRepository.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollectionUploadController.java
Labels: feature

#115 feat: import collections from catalog, decouple image conversion from upload
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollection.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionCatalogImportController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionEventHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/files/FileHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/files/FileUploadBase.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/files/FileUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageConversionService.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageUploadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/utils/flowjs/FlowjsController.java
Labels: feature

#121 fix: cors update
  wipp-backend-core/src/main/java/gov/nist/itl/ssd/wipp/backend/core/rest/CorsFilter.java
Labels: enhancement

#119 feat: name of stitching vector is unique
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorLogic.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorRepository.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorUploadController.java
Labels: enhancement
