Repository usnistgov/WIPP-backend, pull requests merged in 2021-12, with the labels that each got.

#174 docs: Fix Swagger UI URL
  README.md
Labels: documentation

#178 fix: generic data swagger doc
  wipp-backend-application/src/main/java/gov/nist/itl/ssd/wipp/backend/Application.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataDownloadController.java
Labels: bug

#184 feat: added generic data files upload with keycloak
  wipp-backend-application/pom.xml
  wipp-backend-application/src/main/resources/application.properties
  wipp-backend-core/src/main/java/gov/nist/itl/ssd/wipp/backend/core/CoreConfig.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/csvCollection/CsvCollection.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericData.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataDataHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataDownloadController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataEventHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataLogic.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataRepository.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataRepositoryCustom.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataRepositoryImpl.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataResourceProcessor.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFile.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileController.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileHandler.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileRepository.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileRepositoryCustom.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileRepositoryImpl.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/genericfiles/GenericFileUploadController.java
Labels: feature

#186 Feature/upgrade spring boot 2.3
  README.md
  wipp-backend-application/pom.xml
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/core/model/job/JobRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/core/model/workflow/WorkflowRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/csvcollection/CsvCollectionRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/ImagesCollectionRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/jupyternotebook/NotebookRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/pyramid/PyramidRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/stitching/StitchingVectorRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/tensorboard/TensorboardLogsRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/tensorflowmodels/TensorflowModelRepositoryTest.java
  wipp-backend-application/src/test/java/gov/nist/itl/ssd/wipp/backend/data/visualization/VisualizationRepositoryTest.java
  wipp-backend-core/pom.xml
  wipp-backend-core/src/main/java/gov/nist/itl/ssd/wipp/backend/core/rest/PaginationParameterTemplatesHelper.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericData.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataLogic.java
  wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/imagescollection/images/ImageController.java
Labels: dependency-upgrade
